#!/usr/bin/env python3
"""
Generates src/jbm_font.h : 8-bit alpha bitmap font atlases for jbm_menu.

Runs at build-authoring time (host, with PIL). The produced header is committed
so the firmware build itself needs nothing but clang.

For every requested size we rasterise ASCII 32..126 once into a single packed
alpha atlas, plus a small dedicated atlas for the oversized countdown digits.
"""
import os
import sys
from PIL import Image, ImageDraw, ImageFont

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src", "jbm_font.h")

FIRST, LAST = 32, 126
DIGITS = "0123456789:"
MAX_W = 1024        # atlas shelf width
PAD = 24            # generous origin padding while rasterising


def pick_font(bold):
    cands = [
        "/usr/share/fonts/google-noto/NotoSans-Bold.ttf" if bold
        else "/usr/share/fonts/google-noto/NotoSans-Regular.ttf",
        "/usr/share/fonts/liberation-sans-fonts/LiberationSans-Bold.ttf" if bold
        else "/usr/share/fonts/liberation-sans-fonts/LiberationSans-Regular.ttf",
    ]
    for c in cands:
        if os.path.exists(c):
            return c
    raise SystemExit("no usable TTF found")


def rasterise(chars, px, font_path):
    """Return [(bitmap, left_bearing, top_offset, advance)] for each char."""
    font = ImageFont.truetype(font_path, px)
    out = []
    for ch in chars:
        tmp = Image.new("L", (px * 3 + 2 * PAD, px * 3 + 2 * PAD), 0)
        ImageDraw.Draw(tmp).text((PAD, PAD), ch, font=font, fill=255)
        adv = int(round(font.getlength(ch)))
        bbox = tmp.getbbox()
        if bbox is None:                                  # pure whitespace
            out.append((None, 0, 0, adv))
            continue
        x0, y0, x1, y1 = bbox
        out.append((tmp.crop(bbox), x0 - PAD, y0 - PAD, adv))
    return out


def pack(glyphs):
    """Shelf-pack glyphs; returns (canvas, [(sx,sy,w,h,ox,oy,adv)])."""
    order = sorted(range(len(glyphs)), key=lambda i: -(glyphs[i][0].height if glyphs[i][0] else 0))
    placed = {}
    x = y = row_h = 0
    for i in order:
        g = glyphs[i][0]
        if g is None:
            continue
        if x + g.width > MAX_W:
            x = 0
            y += row_h + 1
            row_h = 0
        placed[i] = (x, y)
        x += g.width + 1
        row_h = max(row_h, g.height)
    atlas_w = MAX_W
    atlas_h = y + row_h
    canvas = Image.new("L", (atlas_w, atlas_h), 0)
    meta = []
    for i, (g, ox, oy, adv) in enumerate(glyphs):
        if g is None:
            meta.append((0, 0, 0, 0, 0, 0, adv))
            continue
        sx, sy = placed[i]
        canvas.paste(g, (sx, sy))
        meta.append((sx, sy, g.width, g.height, ox, oy, adv))
    return canvas, meta


def build(chars, px, font_path, tag):
    return pack(rasterise(chars, px, font_path))


def emit(fh, name, chars, px, canvas, metrics, bold):
    fh.write("/* --- %s : %dpx%s --- */\n" % (name, px, " bold" if bold else ""))
    fh.write("static const char %s_data[] = {\n" % name)
    raw = canvas.tobytes()
    for i in range(0, len(raw), 24):
        fh.write(",".join(str(b) for b in raw[i:i + 24]) + ",\n")
    fh.write("};\n")
    fh.write("static const short %s_meta[][7] = {\n" % name)
    for m in metrics:
        fh.write("{%d,%d,%d,%d,%d,%d,%d},\n" % m)
    fh.write("};\n")
    top = min([m[5] for m in metrics if m[3]], default=0)
    bot = max([m[5] + m[3] for m in metrics if m[3]], default=px)
    fh.write("#define %s_ATLAS_W %d\n" % (name, canvas.width))
    fh.write("#define %s_ATLAS_H %d\n" % (name, canvas.height))
    fh.write("#define %s_PX %d\n" % (name, px))
    fh.write("#define %s_TOP %d\n" % (name, top))
    fh.write("#define %s_BOT %d\n" % (name, bot))
    fh.write("#define %s_FIRST %d\n" % (name, ord(chars[0])))
    fh.write("#define %s_COUNT %d\n\n" % (name, len(metrics)))


def main():
    bold_path = pick_font(True)
    reg_path = pick_font(False)
    ascii_chars = [chr(c) for c in range(FIRST, LAST + 1)]

    with open(OUT, "w") as fh:
        fh.write("/* Generated by tools/gen_font.py -- do not edit by hand. */\n")
        fh.write("#ifndef JBM_FONT_H\n#define JBM_FONT_H\n\n")

        sizes = [
            ("F20", 20, False),
            ("F34", 34, False),
            ("F48", 48, True),
            ("FDIG", 132, True),
        ]
        for tag, px, bold in sizes:
            chars = list("0123456789:") if tag == "FDIG" else ascii_chars
            canvas, metrics = build(chars, px, bold_path if bold else reg_path, tag)
            emit(fh, tag, chars, px, canvas, metrics, bold)
            print("%-5s %3dpx  %5d bytes" % (tag, px, len(canvas.tobytes())))

        fh.write("#endif\n")
    print("wrote", os.path.abspath(OUT), os.path.getsize(OUT), "bytes")


if __name__ == "__main__":
    main()
